[build-system]
requires = ["setuptools>=61", "setuptools-scm", "numpy>=1.17,<2", "cython>=0.18", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["abbott_features"]

[tool.setuptools_scm]
version_scheme = "post-release"
local_scheme = "no-local-version"

[tool.hatch.metadata]
allow-direct-references = true # remove once ngio-dev is integrated in ngio
# Clean up the source distribution to avoid big tag.gz files
[tool.hatch.build.targets.sdist]
exclude = [
    # Exclude tests from the source distribution
    "tests",
    # Exclude typically large files and directories that are not needed
    # This might not exists or be named differently in your project
    # TBD if we want to include these or not
    "docs",
    "data",
    "examples",
    "notebooks",
    ".github",
    # Remove all jupyter notebook and checkpoints
    "**/*.ipynb_checkpoints",
    "**/*.ipynb",
    # NB all things in .gitignore are excluded by default of hatchling
]

# Project metadata (see https://peps.python.org/pep-0621)
[project]
name = "abbott-features"
dynamic = ["version"]
description = "A fractal task collection to extract multi-scale features from 3D structures"
readme = "README.md"
license = { text = "BSD-3-Clause" }
authors = [{ name = "Ruth Hornbachner", email = "ruth.hornbachner@uzh.ch" }]

# Required Python version and dependencies
requires-python = ">=3.11,<3.14"
dependencies = ["pandas",
                "polars",
                "scipy",
                "scikit-learn",
                "scikit-image",
                "spatial-image",
                "seaborn",
                "itk<5.4.4", 
                "strenum",
                "numba",
                "networkx[default]",
                "contourpy",
                "fractal-task-tools",
                "ngio==1.0.0",
                "lxml",
                "h5py"
                ]

# Optional dependencies 
[project.optional-dependencies]

test = ["pytest", "requests", "jsonschema", "devtools"]

dev = [
    "notebook",
    "devtools",
    "hatch",
    "pytest",
    "requests",
    "jsonschema",
    "ruff",
    "pre-commit",
]

# https://docs.astral.sh/ruff
[tool.ruff]
line-length = 88
target-version = "py311"
src = ["src"]

# https://docs.astral.sh/ruff/rules
[tool.ruff.lint]
pydocstyle = { convention = "google" }
select = [
    "E",    # style errors
    "W",    # style warnings
    "F",    # flakes
    "D",    # pydocstyle
    "D417", # Missing argument descriptions in Docstrings
    "I",    # isort
    "UP",   # pyupgrade
    "C4",   # flake8-comprehensions
    "B",    # flake8-bugbear
    "A001", # flake8-builtins
    "RUF",  # ruff-specific rules
    "TCH",  # flake8-type-checking
    "TID",  # flake8-tidy-imports
]
extend-select = [
    "D417", # Missing argument descriptions in Docstrings
]
ignore = [
    "B008", # Do not perform function calls in argument defaults
    "C408", # Dictionary comprehension
    "D401", # First line should be in imperative mood (remove to opt in)
    "D415", # First line should end with a period (remove to opt in)
    "D101", # Missing docstring in public class (remove to opt in)
    "D102", # Missing docstring in public module (remove to opt in)
    "D103", # Missing docstring in public module (remove to opt in)
    "D105", # Missing docstring in magic method (remove to opt in)
    "D107", # Missing docstring in `__init__` (remove to opt in)
]

[tool.ruff.lint.per-file-ignores]
"tests/*.py" = ["D", "S"]

# https://docs.astral.sh/ruff/formatter/
[tool.ruff.format]
docstring-code-format = true
docstring-code-line-length = 89
skip-magic-trailing-comma = false  #// filepath: /Users/ruthh/Pelkmans/Fractal/abbott-features/pyproject.toml

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.dependencies]
c-compiler = "*"
cxx-compiler = "*"

[tool.pixi.pypi-dependencies]
abbott_features = { path = ".", editable = true }

[tool.pixi.environments]
default = { solve-group = "default" }
dev = { features = ["dev"], solve-group = "default" }
test = { features = ["test"], solve-group = "default" }

[tool.pixi.tasks]
install-pre-commit = { cmd = ["pre-commit", "install"] }
format-imports = { cmd = ["ruff", "check", "--select", "I", "--fix"] }
format-code = { cmd = ["ruff", "format", "."] }

create-manifest = { cmd = [
    "fractal-manifest",
    "create",
    "--package",
    "abbott_features",
] }

test = { cmd = ["pytest", "./tests/"] }

init-tasks = [
    { task = "install-pre-commit", environment = "dev" },
    { task = "format-code", environment = "dev" },
    { task = "format-imports", environment = "dev" },
    { task = "create-manifest", environment = "dev" },
    { task = "test", environment = "dev" },
]